EMAIL="dcvernet@gmail.com"
REALNAME="David Vernet"
CLIENT_ID="957879641588-jdka6lfclvusnd9iqtnqet1139psq9s1.apps.googleusercontent.com"
AUTH_METHOD="oauth2"
IMAP_URL="imap.gmail.com:993"
SMTP_URL="smtp.gmail.com:587"
