EMAIL="void@manifault.com"
REALNAME="David Vernet"
CLIENT_ID="550736786223-bggbrd3ulrk1i3t7e0irls92ijhunl7g.apps.googleusercontent.com"
AUTH_METHOD="oauth2"
IMAP_URL="imap.gmail.com:993"
SMTP_URL="smtp.gmail.com:587"
